carts/urls.py
from django.urls import path
from .views import cart_view, add_product_to_cart, remove_product_from_cart

urlpatterns = [
    path('view/', cart_view, name="view"),
    path('add/', add_product_to_cart, name="add"),
    path('remove/', remove_product_from_cart, name="remove")
]

djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import RedirectView

from orders.views import place_order, OrdersListView
from . import settings
from .views import home_page, UserLoginView, register_view

urlpatterns = [
    path("favicon.ico/", RedirectView.as_view(url='/static/favicon.ico')),
    path("", home_page, name="home"),

    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", register_view, name="register"),

    path("cart/", include('carts.urls')),
    path("products/", include("products.urls", namespace="products")),
    path('place-order/', place_order, name="place-order"),
    path('orders/', OrdersListView.as_view()),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import ProductListView, ProductDetailSlugView

app_name = "products"

urlpatterns = [
    path('all/', ProductListView.as_view(), name="all"),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name="detail")
]

products/models.py
# from django.contrib.auth.mixins import LoginRequiredMixin
import os

from django.db import models
# LoginRequiredMixin
from django.db.models.signals import pre_save
from django.urls import reverse

from products.utils import unique_slug_generator


def get_file_ext(filepath):
    base_name = os.path.basename(filepath)
    _, extension = os.path.splitext(base_name)
    return extension


def upload_image_path(instance, filename):
    extension = get_file_ext(filename)

    final_filename = '{product_slug}{ext}'.format(product_slug=instance.slug, ext=extension)
    return "products/{final_filename}".format(
        final_filename=final_filename
    )


class Product(models.Model):
    title = models.CharField(max_length=128, blank=False, unique=True)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=20, blank=False)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    quantity_available = models.IntegerField(blank=False, default=0)

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __repr__(self):
        return "Product(title={})".format(self.title)


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from django.http import Http404

from django.views.generic import ListView, DetailView

from carts.models import Cart
from .models import Product
from django.shortcuts import get_object_or_404


class ProductDetailSlugView(DetailView):
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            cart_obj = Cart.objects.obtain_user_cart(self.request.user)
            context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Product, slug=slug)


class ProductListView(ListView):
    template_name = "products/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            cart_obj = Cart.objects.obtain_user_cart(self.request.user)
            context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        return Product.objects.all()

products/templates/products/detail.html
{% extends "base.html" %}

{% block content %}
    <div style="font-size: 24px;margin-bottom: 40px;padding-top: 40px;">Product Details</div>
{% include "products/product-card.html" with product=object %}

{% endblock %}

products/templates/products/list.html
{% extends "base.html" %}

{% block content %}
    <div style="font-size: 24px;margin-bottom: 40px;padding-top: 40px;">Our Product Catalogue</div>
    <div class="card-columns">
{% for object in object_list  %}
    {% include "products/product-card.html" with product=object %}
{#    <p>{{ product.title }} </p>#}
{% endfor %}
    </div>

{% endblock %}

products/templates/products/product-card.html
{% load static %}
{% url 'products:all' as all_products_url %}

<div class="card" style="margin-top:15px;">
  <h5 class="card-header" style="background-color: {% if product.quantity_available > 0 %} lightgreen {% else %} red {% endif %}">{{ product.title }}<span style="float:right">{% if product.quantity_available > 0 %} Available {% else %} Out of Stock {% endif %}</span></h5>
    <img class="card-img-top" {% if product.image %} src="{{ product.image.url }}" {% else %} src="{% static 'img/not-found-image.jpg' %}" {% endif %} style="display:block;width:200px; margin: 24px auto 0px auto;" alt="{{ product.slug }}">
  <div class="card-body">
    <h5 class="card-title">Price: ${{ product.price }}</h5>
    <p class="card-text">{{ product.description }}</p>
    {% if all_products_url == request.path %}
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary" id="{{ product.slug }}">View</a>
    {% endif %}
      {% if product.quantity_available > 0 and request.user.is_authenticated %}
          <button onclick="addToCart = () => {
              let prevCount = document.getElementById('cart-items-number').innerHTML
                if (this.innerHTML.includes('Add')) {
                  fetch('/cart/add?product_slug=' + '{{ product.slug }}')
                  .then(res => res.json())
                  .then((res) => {
                      console.log('Response from Backend Server: ', res);
                      this.innerHTML = 'Remove from Cart'
                      this.classList.add('btn-danger')
                      this.classList.remove('btn-primary')
                      document.getElementById('cart-items-number').innerHTML = '' + (parseInt(prevCount) + 1);
                  })
                } else {
                  fetch('/cart/remove?product_slug=' + '{{ product.slug }}')
                  .then(res => res.json())
                  .then((res) => {
                      console.log('Response from Backend Server: ', res);
                      this.innerHTML = 'Add from Cart'
                      this.classList.remove('btn-danger')
                      this.classList.add('btn-primary')
                      document.getElementById('cart-items-number').innerHTML = '' + (parseInt(prevCount) - 1);
                  })
                }
          }
          addToCart()" class="btn {% if product not in cart.products.all %} btn-primary {% else %} btn-danger {% endif %}">

          {% if product not in cart.products.all %}  Add To Cart {% else %} Remove From Cart {% endif %}
          </button>
      {% endif %}
  </div>
</div>